### ISSUE TITLE
Add images for sets

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/api.mtgdb.info#19]
Have the icon image for each set

**Comment by jesseflorig** [comment]
+1

How about rarity icons as well?

**Comment by ontehfritz** [comment]
I will open another issue for the rarity icons :+1:

**Comment by alotau** [comment]
+1, various resolutions would be handy too.  You know, since we're asking for stuff.

**Comment by ontehfritz** [comment]
this will be covered by: https://github.com/planeswalkers/api.mtgdb.info/issues/42
