### ISSUE TITLE
Search method for cards and sets

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/api.mtgdb.info#22]
Create a search method that will allow a string to be searched for. This feature will rely on mongodb's new text search feature.

**Comment by ontehfritz** [comment]
A simple search by card name will be provided in the next release. Futures: Mongodb released a beta for textual search engine for mongo, we will use this in testing and release the full text support once mongodb release the production ready engine. To build ranking, indexing, and search querying engine our selves would take away from the goal of the project.

**Comment by AnthonyMDev** [comment]
So, right now, if I use a filter, it filters OUT those cards, and I get a list of everything else. This feature will be the opposite of that correct? This will give me JUST the cards I'm searching for?
Hoping to see this implemented soon!

**Comment by ontehfritz** [comment]
current filters work by including everything by the field and the value, it is like a where clause, it is an exact match, the search function will be different. It will be textual search, without getting into to many details, it will be more like a google type search,were the search results have ranking and relevance.

**Comment by ontehfritz** [comment]
Simple match search is implemented as an Alpha feature. This will match text anywhere in the card name field. This is placeholder until "full text search" is ready.

**Comment by ontehfritz** [comment]
Advanced search implemented, close this for now, not sure if we will implement text search with mongodb
