### ISSUE TITLE
Filter fields, allow to specify fields to be returned in the query

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/api.mtgdb.info#25]
Allow the ability to select which fields to be returned in the query, this is good if you just want a list of card ids, or just the names etc

**Comment by AnthonyMDev** [comment]
This is the feature that I would appreciate most of this api. Thanks for the awesome API!

**Comment by ontehfritz** [comment]
no problem, love to hear that developers like it!

**Comment by ontehfritz** [comment]
Implemented on /cards/ and sets/[id]/cards. 

http://api.mtgdb.info/cards/?fields=id,name,cardsetid 
http://api.mtgdb.info/sets/THS/cards/?fields=setnumber,id,name

If it is needed on other methods a new issue can be created.
