### ISSUE TITLE
Remove Image Url in JSON output? Need your input!

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/api.mtgdb.info#39]
For those keeping track of the API. To save some bandwidth, An idea is to remove the cardImage field. 

The images would still be hosted at: 

Main image: http://api.mtgdb.info/content/card_images/{multiverseId}.jpeg
hires large: http://api.mtgdb.info/content/hi_res_card_images/{multiverseId}.jpg

This would be stated in the documentation where to find the images. 

I am all for the idea as it would save some bandwidth. The api wrappers/drivers and your wrappers can fill in this info. 

Leave your comments!

**Comment by phylaxis** [comment]
Seem like it would be OK to me.

**Comment by ontehfritz** [comment]
This will be coming in affect: Mar 9 2014

Please make changes to in your code the URLs are as follows: 

http://api.mtgdb.info/content/card_images/{mutliverseid}.jpeg

https://api.mtgdb.info/content/card_images/{mutliverseid}.jpeg

Large Hi-Res Images

http://api.mtgdb.info/content/hi_res_card_images/{multiverseid}.jpg

https://api.mtgdb.info/content/hi_res_card_images/{multiverseid}.jpg

**Comment by jesseflorig** [comment]
+1

**Comment by ontehfritz** [comment]
:+1:  POW!
