### ISSUE TITLE
Add Field for Related Cards

### ISSUE THREAD

**Issue by jesseflorig** [ontehfritz/api.mtgdb.info#41]
Such as Scorned Villager/Moonscarred Werewolf

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=262659

Or B.F.M.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9844

**Comment by ontehfritz** [comment]
Thanks for this! I will have to look into loading the other card faces.

**Comment by ontehfritz** [comment]
Add "relatedCardId"  to associated cards that need another card to be brought into play or have more than one card face.

**Comment by ontehfritz** [comment]
field has been added, however it won't be populated yet, all related cards ids = 0. This field will be populated when the open db features are released, then this issue can be closed

**Comment by ontehfritz** [comment]
Fixed Scorned Villager/Moonscarred Werewolf with the card change request feature. BFM is missing its other half so I will close this and create an issue for it.
