### ISSUE TITLE
Translations into other languages ?

### ISSUE THREAD

**Issue by jcrombez** [ontehfritz/api.mtgdb.info#47]
Any chance to see more languages available in the future ?

**Comment by ontehfritz** [comment]
I would  like to support other languages, unfortunately I can't see it happening in the near future, it won't be in the queue until the major features have been implemented. Sorry :)

**Comment by jcrombez** [comment]
Ok, thank you :)

**Comment by ontehfritz** [comment]
This will be worked on after it is out of beta, closing for now.
