### ISSUE TITLE
Add foils

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/api.mtgdb.info#57]
Add the foil images plus a new field to indicate if a card has foils or not

**Comment by ontehfritz** [comment]
I need a source for this info! I can't find a list of cards that have a foil print. Preferably with the multiverse Id.

**Comment by alotau** [comment]
From Urza's Legacy onward, all cards have a foil version. (http://wiki.mtgsalvation.com/article/Foil_card).

That doesn't cover special cards (FNM, Player rewards, etc) but in reality, those cards should be considered in their own sets and are automatically considered foil.  Am I missing the point of this issue?

**Comment by ontehfritz** [comment]
This is a request I got via email, I wasn't sure if every card has a foil version. If this is the case then I just need to get the images for the foil version.

**Comment by ontehfritz** [comment]
Looking at foil images scanned, you can't really tell they are foils. The request is looking to be not really relevant any more. Especially if every card potentially has a foil. Closing this for now.
