### ISSUE TITLE
"random" from a set is not so random

### ISSUE THREAD

**Issue by alotau** [ontehfritz/api.mtgdb.info#64]
Each time I use this request:

https://api.mtgdb.info/sets/ALA/cards/random

I get "Battlegrace Angel".  Tried it 5 or 6 times.  Didn't test any other sets yet.

**Comment by ontehfritz** [comment]
that set specifically is having issues, I tried 5 other sets and they seem ok. Looking into

**Comment by alotau** [comment]
Weird.  I totally picked Alara at random for my test.  It was the first and only set that I chose.
