### ISSUE TITLE
Number of card id's != total

### ISSUE THREAD

**Issue by alotau** [ontehfritz/api.mtgdb.info#80]
Did something change in the API?  Currently when fetching cards by set like:

http://api.mtgdb.info/sets/10E

the value for 'total' is different than the number of cardIds that are returned.

Is this an issue with tokens being included in the 'total' but not having a cardId?

**Comment by ontehfritz** [comment]
Yes! I still need to get into this it does have something to do with promo and token cards (and some unknowns I have to look into).  I was using the cardId for counts, but when using paging etc it was messing it up royally. 

https://github.com/planeswalkers/api.mtgdb.info/issues/75

What the plan is to get all the funtionality  opendb stuff and deck builder complete, the api's first priority is mtgdb.info fronted. Once all that is built, then it is time to hammer the quality  in from data to code before anything else is built. So it will get there.  Bare with me!

**Comment by alotau** [comment]
I'm not too worried about it, just noticed when one of my junit tests started failing.  Never used unit testing before... quite handy!

**Comment by ontehfritz** [comment]
It gets published counts now so it, its all good. I will close this! But promos and tokens will be dealt with.
