### ISSUE TITLE
Duplicate id's in Fate Reforged set (2015)

### ISSUE THREAD

**Issue by calamarico** [ontehfritz/api.mtgdb.info#92]
The id card 391783 is repeated on that set.

To be more specified, in cardsId array, this id is in positions 1 and 118

**Comment by ontehfritz** [comment]
Duplicates should be removed now, don't know what happened with that, also if might be better to use: 
https://api.mtgdb.info/sets/frf/cards to go through all the cards. Anyway let me know if the update resolves the issue. If so I will close this.

**Comment by calamarico** [comment]
Now it's resolved :+1:  no more duplicates are there.

Thanks!!!!!

**Comment by ontehfritz** [comment]
:+1:
