### ISSUE TITLE
Make a better default value for Release Date

### ISSUE THREAD

**Issue by Xynariz** [ontehfritz/api.mtgdb.info#96]
When a release date is null, it is invalid JSON, and will cause crashing of JSON parsers.  There are (currently) 352 cards that have "releasedAt":null , and all of those cause issues.  

Two examples are Charcoal Diamond (http://api.mtgdb.info/cards/389463) and Wrath of God (http://api.mtgdb.info/cards/386298).

Perhaps you could use a default "valid date" that is actually meaningless?  (e.g. January 1, 1900)

**Comment by cokeeffekt** [comment]
"releasedAt":null is not invalid JSON, null is fine for use in this scenario.

**Comment by Xynariz** [comment]
Hmmm.. maybe the issue is with the Java wrapper around the API.  I'll post the issue there.
